-- Миграция вверх: statuses

-- +goose Up
-- +goose StatementBegin

-- Create statuses table with constraints and indexes
create table if not exists statuses (
        id integer generated by default as identity primary key,
        name text not null constraint statuses_name_check check (name <> ''::text),
        description text, -- Optional description for the status
        created_at timestamptz default now() not null,
        updated_at timestamptz default now() not null
);

-- Comment for documentation
comment on table statuses is 'Статусы задач (например, "В работе", "Завершена")';

-- Unique index on name to prevent duplicate statuses
create unique index if not exists statuses_name_idx on statuses (name);

-- Trigger for updated_at (reuses the function from users migration)
create trigger update_statuses_updated_at before update on statuses
    for each row execute function update_updated_at_column();
-- Insert initial data
insert into statuses (name, description) values
     ('В процессе', 'Статус задачи находящийся в процессе выполнения'),
     ('Выполнено', 'Статус выполненной задачи'),
     ('Просрочено', 'Статус задачи которая была просрочена'),
     ('Завершено', 'Статус завершенной задачи');
-- +goose StatementEnd
