-- Миграция вверх: create_users_table

-- +goose Up
-- +goose StatementBegin

-- Create users table with constraints, indexes, and audit fields
create table if not exists users (
    id integer generated by default as identity primary key,
    tg_id integer not null,
    name text not null constraint users_name_check check (name <> ''::text),
    timezone text not null default 'UTC',
    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

-- Comment for documentation
comment on table users is 'Пользователи Telegram с уникальным tg_id';

-- Unique index on tg_id to prevent duplicates
create unique index if not exists users_tg_id_idx on users (tg_id);

-- Function to update updated_at automatically
create or replace function update_updated_at_column()
    returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

-- Trigger for users table
create trigger update_users_updated_at before update on users
    for each row execute function update_updated_at_column();
-- +goose StatementEnd