-- Миграция вверх: tasks
-- +goose Up

-- Create tasks table with FK, constraints, indexes, and audit fields
create table if not exists tasks (
        id integer generated by default as identity primary key,
        description text not null constraint tasks_description_check check (description <> ''::text),
        deadline timestamptz, -- Nullable for tasks without deadline
        priority integer, -- Optional: 1-10 for task priority, add check if needed
        status_id integer references statuses(id) on delete set null, -- FK to statuses, set null if status deleted
        user_id integer not null references users(id) on delete cascade, -- FK to users, cascade delete
        created_at timestamptz default now() not null,
        updated_at timestamptz default now() not null
);

-- Comment for documentation
comment on table tasks is 'Задачи пользователей с дедлайнами и статусами';

-- Indexes for performance
create index if not exists tasks_user_id_idx on tasks (user_id); -- For JOIN with users
create index if not exists tasks_status_id_idx on tasks (status_id); -- For JOIN with statuses
create index if not exists tasks_deadline_idx on tasks (deadline); -- For filtering by deadline
create index if not exists tasks_priority_idx on tasks (priority); -- For sorting by priority

-- Trigger for updated_at (reuses the function)
create trigger update_tasks_updated_at before update on tasks
    for each row execute function update_updated_at_column();
-- +goose StatementEnd